# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_de_factura',
            field=models.DateTimeField(default=51561),
            preserve_default=False,
        ),
    ]
